services:
  db:
    image: postgres:17
    container_name: dhg503-db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: dhg503
    ports:
      - "10503:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  pgdata:
